name: Deploy to Koyeb

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven (skip tests)
        run: mvn -B -DskipTests package

      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          # Required: create KOYEB_API_TOKEN in repo secrets
          api_token: ${{ secrets.KOYEB_API_TOKEN }}
          app_name: swapi-challenge
          service_name: backend
          builder: dockerfile
          dockerfile: Dockerfile
          ports: 8080:http
          env: |
            JAVA_OPTS=-Xms256m -Xmx512m
