services:
  - type: web
    name: swapi-challenge
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: -Xms256m -Xmx512m
    healthCheckPath: /
