server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:swapi;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas desde tus @Entity
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging.level.root: INFO

app:
  jwt:
    secret: "c2VjcmV0LXN1cGVyLWxhcmdvLXBhcmEtdGVzdC1lbmNvZGU=" # Base64
    expiration-ms: 3600000

swapi:
  base-url: "https://www.swapi.tech/api"
